#path_file: "/home/roboticslab/colcon_ws/src/create3_controller/results/odom_roomba20.csv"
path_file: "/home/redwan/colcon_ws/src/create3_controller/results/odom_roomba20.csv"
xml_file: "/home/redwan/colcon_ws/src/create3_controller/config/bt_controller.xml"
controller:
    position:
      gains:
        kp: 1.0
        kd: 0.5
        ki: 0
      stability:
        dt: 30 # ms
        deadzone: 0.1 #m
        timeout: 500 # (dt * timeout) ms
    orientation:
      gains:
        kp: 2.80
        kd: 0.5
        ki: 0
      stability:
        dt: 30 # ms
        deadzone: 0.06 #rad
        timeout: 500 # (dt * timeout) ms